title: rohan's playground
name: Rohan Harikumar
user_description: <strike>Pro</strike>grammer
notes_url: ""
profile_pic: /assets/img/profile.jpeg
favicon: /assets/img/favicon.png
copyright_name: Not a member of the Cheezburger© Group.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://rohanharikumar.com"
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

exclude: [old]

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

disqus:
  shortname: rohanharikumar 

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
