site: rohan
url: #yoururl
title: rohan
description: I have too many hobbies.
twitter:
  username: rohanharikr
  card: summary
  creator: #yourusername
author:
  twitter: rohanharikr
  name: rohan
  avatar:
  email: rohanharikumar80@gmail.com
  url: #yoururl
permalink: pretty

baseurl: ""

highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  # tags:
  #   output: true
  #   permalink: '/tag/:path/'
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"